export const navigation = [
    {
        id: '1',
        title: 'Салаты',
        link: 'salads',
        icon: '/src/assets/icons/salad.svg',
        tabs: [
            { title: 'Мясные салаты', link: 'salads/meat-salads' },
            { title: 'Рыбные салаты', link: 'salads/fish-salads' },
            { title: 'Овощные салаты', link: 'salads/vegetable-salads' },
            { title: 'Теплые салаты', link: 'salads/warm-salads' },
        ],
    },
    {
        id: '2',
        title: 'Закуски',
        link: 'appetizers',
        icon: '/src/assets/icons/snacks.svg',
        tabs: [
            { title: 'Мясные закуски', link: 'appetizers/meat-appetizers' },
            { title: 'Рыбные закуски', link: 'appetizers/fish-appetizers' },
            { title: 'Овощные закуски', link: 'appetizers/vegetable-appetizers' },
            { title: 'Теплые закуски', link: 'appetizers/warm-appetizers' },
            { title: 'Бутерброды', link: 'appetizers/sandwiches' },
            { title: 'Фастфуд', link: 'appetizers/fast-food' },
        ],
    },
    {
        id: '3',
        title: 'Первые блюда',
        link: 'soups',
        icon: '/src/assets/icons/soup.svg',
        tabs: [
            { title: 'Мясные супы', link: 'soups/meat-soups' },
            { title: 'Овощные супы', link: 'soups/vegetable-soups' },
            { title: 'Бульоны', link: 'soups/broths' },
            { title: 'Холодные супы', link: 'soups/cold-soups' },
            { title: 'Диетические супы', link: 'soups/diet-soups' },
        ],
    },
    {
        id: '4',
        title: 'Вторые блюда',
        link: 'main-courses',
        icon: '/src/assets/icons/pan.svg',
        tabs: [
            { title: 'Мясные', link: 'main-courses/meat-dishes' },
            { title: 'Рыбные', link: 'main-courses/fish-dishes' },
            { title: 'Овощные', link: 'main-courses/vegetable-dishes' },
            { title: 'Из птицы', link: 'main-courses/poultry-dishes' },
            { title: 'Из грибов', link: 'main-courses/mushroom-dishes' },
            { title: 'Из субпродуктов', link: 'main-courses/offal-dishes' },
            { title: 'На пару', link: 'main-courses/steamed-dishes' },
            { title: 'Пельмени, вареники', link: 'main-courses/dumplings' },
            { title: 'Мучные гарниры', link: 'main-courses/flour-side-dishes' },
            { title: 'Овощные гарниры', link: 'main-courses/vegetable-side-dishes' },
            { title: 'Пицца', link: 'main-courses/pizza' },
            { title: 'Суши', link: 'main-courses/sushi' },
        ],
    },
    {
        id: '5',
        title: 'Десерты, выпечка',
        link: 'desserts',
        icon: '/src/assets/icons/dessert.svg',
        tabs: [
            { title: 'Блины и оладьи', link: 'desserts/pancakes' },
            { title: 'Пироги и пончики', link: 'desserts/pies-donuts' },
            { title: 'Торты', link: 'desserts/cakes' },
            { title: 'Рулеты', link: 'desserts/rolls' },
            { title: 'Кексы и маффины', link: 'desserts/cupcakes-muffins' },
            { title: 'Сырники и ватрушки', link: 'desserts/cheesecakes' },
            { title: 'Из слоеного теста', link: 'desserts/puff-pastry' },
            { title: 'Из заварного теста', link: 'desserts/choux-pastry' },
            { title: 'Из дрожжевого теста', link: 'desserts/yeast-dough' },
            { title: 'Булочки и сдоба', link: 'desserts/buns-pastries' },
            { title: 'Хлеб', link: 'desserts/bread' },
            { title: 'Тесто для пиццы', link: 'desserts/pizza-dough' },
            { title: 'Кремы', link: 'desserts/creams' },
        ],
    },
    {
        id: '6',
        title: 'Блюда на гриле',
        link: 'grill',
        icon: '/src/assets/icons/grill.svg',
        tabs: [
            { title: 'Говядина', link: 'grill/grilled-beef' },
            { title: 'Свинина', link: 'grill/grilled-pork' },
            { title: 'Птица', link: 'grill/grilled-poultry' },
            { title: 'Рыба', link: 'grill/grilled-fish' },
            { title: 'Грибы', link: 'grill/grilled-mushrooms' },
            { title: 'Овощи', link: 'grill/grilled-vegetables' },
        ],
    },
    {
        id: '7',
        title: 'Веганская кухня',
        link: 'vegan-cuisine',
        icon: '/src/assets/icons/vegan.svg',
        tabs: [
            { title: 'Закуски', link: 'vegan-cuisine/appetizers' },
            { title: 'Первые блюда', link: 'vegan-cuisine/soups' },
            { title: 'Вторые блюда', link: 'vegan-cuisine/main-dishes' },
            { title: 'Гарниры', link: 'vegan-cuisine/side-dishes' },
            { title: 'Десерты', link: 'vegan-cuisine/desserts' },
            { title: 'Выпечка', link: 'vegan-cuisine/bakery' },
            { title: 'Сыроедческие блюда', link: 'vegan-cuisine/raw-food' },
            { title: 'Напитки', link: 'vegan-cuisine/drinks' },
        ],
    },
    {
        id: '8',
        title: 'Детские блюда',
        link: 'kids',
        icon: '/src/assets/icons/child.svg',
        tabs: [
            { title: 'Первые блюда', link: 'kids/soups' },
            { title: 'Вторые блюда', link: 'kids/main-dishes' },
            { title: 'Гарниры', link: 'kids/side-dishes' },
            { title: 'Выпечка', link: 'kids/bakery' },
            { title: 'Без глютена', link: 'kids/gluten-free' },
            { title: 'Без сахара', link: 'kids/sugar-free' },
            { title: 'Без аллергенов', link: 'kids/allergen-free' },
            { title: 'Блюда для прикорма', link: 'kids/baby-food' },
        ],
    },
    {
        id: '9',
        title: 'Лечебное питание',
        link: 'diet',
        icon: '/src/assets/icons/healthy.svg',
        tabs: [
            { title: 'Детская диета', link: 'diet/kids-diet' },
            { title: 'Диета №1', link: 'diet/diet-1' },
            { title: 'Диета №2', link: 'diet/diet-2' },
            { title: 'Диета №3', link: 'diet/diet-3' },
            { title: 'Диета №5', link: 'diet/diet-5' },
            { title: 'Диета №6', link: 'diet/diet-6' },
            { title: 'Диета №7', link: 'diet/diet-7' },
            { title: 'Диета №8', link: 'diet/diet-8' },
            { title: 'Диета №9', link: 'diet/diet-9' },
            { title: 'Диета №10', link: 'diet/diet-10' },
            { title: 'Диета №11', link: 'diet/diet-11' },
            { title: 'Диета №12', link: 'diet/diet-12' },
            { title: 'Диета №13', link: 'diet/diet-13' },
            { title: 'Диета №14', link: 'diet/diet-14' },
            { title: 'Без глютена', link: 'diet/gluten-free' },
            { title: 'Без аллергенов', link: 'diet/allergen-free' },
        ],
    },
    {
        id: '10',
        title: 'Национальные',
        link: 'cuisine',
        icon: '/src/assets/icons/international.svg',
        tabs: [
            { title: 'Американская кухня', link: 'cuisine/american' },
            { title: 'Армянская кухня', link: 'cuisine/armenian' },
            { title: 'Греческая кухня', link: 'cuisine/greek' },
            { title: 'Грузинская кухня', link: 'cuisine/georgian' },
            { title: 'Итальянская кухня', link: 'cuisine/italian' },
            { title: 'Испанская кухня', link: 'cuisine/spanish' },
            { title: 'Китайская кухня', link: 'cuisine/chinese' },
            { title: 'Мексиканская кухня', link: 'cuisine/mexican' },
            { title: 'Паназиатская кухня', link: 'cuisine/pan-asian' },
            { title: 'Русская кухня', link: 'cuisine/russian' },
            { title: 'Турецкая кухня', link: 'cuisine/turkish' },
            { title: 'Французская кухня', link: 'cuisine/french' },
            { title: 'Шведская кухня', link: 'cuisine/swedish' },
            { title: 'Японская кухня', link: 'cuisine/japanese' },
            { title: 'Другая кухня', link: 'cuisine/other' },
        ],
    },
    {
        id: '11',
        title: 'Соусы',
        link: 'sauces',
        icon: '/src/assets/icons/sauce.svg',
        tabs: [
            { title: 'Соусы мясные', link: 'sauces/meat' },
            { title: 'Соусы сырные', link: 'sauces/cheese' },
            { title: 'Маринады', link: 'sauces/marinades' },
        ],
    },
    {
        id: '12',
        title: 'Напитки',
        link: 'drinks',
        icon: '/src/assets/icons/drink.svg',
        tabs: [
            { title: 'Соки и фреши', link: 'drinks/juices' },
            { title: 'Смузи', link: 'drinks/smoothies' },
            { title: 'Компоты', link: 'drinks/compotes' },
            { title: 'Кисели', link: 'drinks/jelly' },
            { title: 'Кофе', link: 'drinks/coffee' },
            { title: 'Лечебный чай', link: 'drinks/medicinal-tea' },
            { title: 'Квас', link: 'drinks/kvass' },
            { title: 'Коктейли', link: 'drinks/cocktails' },
            { title: 'Алкогольные', link: 'drinks/alcoholic' },
        ],
    },
    {
        id: '13',
        title: 'Заготовки',
        link: 'preserves',
        icon: '/src/assets/icons/workpieces.svg',
        tabs: [],
    },
];
